version: 2

variables:
  update_conda: &update_conda
    run:
      name: Update conda
      command: conda update --yes conda
  install_from_dev_requirements_py36: &install_from_dev_requirements_py36
    run:
      name: Install from dev-requirements-py36.yml
      command: |
        echo 'export CI_JOB_PY_YAML="$CI_JOB_PY_YAML"' >> $BASH_ENV
        conda env create --name kipoi-env -f dev-requirements-py36.yml
        source activate kipoi-env
        pip install -e '.[develop]'
        git lfs install
        # ln -s /opt/conda/bin/python /usr/bin/python      
  export_shortcuts: &export_shortcuts
    run:
      name: Export shortcuts
      command: |
        # for no good reason the wrong version of pytest is choosen by default...
        echo 'export PYTEST=$(conda info --base)/envs/kipoi-env/bin/pytest' >> $BASH_ENV
  kipoi_ls: &activate_and_kipoi_ls
    run:
      name: List kipoi packages
      command: |
        source activate kipoi-env
        kipoi ls
  run_tests: &run_tests
    run:
      name: Run tests
      command: |
        source activate kipoi-env
        mkdir test-reports
        py.test --cov=kipoi_veff/ tests/ -n 4 --no-cov-on-fail --junitxml=test-reports/junit.xml
  run_coveralls: &run_coveralls
    run:
      name: run coveralls
      command: |
        source activate kipoi-env
        coveralls || true
  store_test_results: &store_test_results
    store_test_results:
      path: test-reports
  store_test_artifacts: &store_test_artifacts
    store_artifacts:
      path: test-reports
      destination: test-reports


jobs:

  test-py36:
    docker:
      - image: continuumio/miniconda3:4.7.10
    working_directory: ~/repo
    steps:
      - checkout
      - *update_conda
      - *install_from_dev_requirements_py36
      - *export_shortcuts
      - *activate_and_kipoi_ls
      - *run_tests
      - *run_coveralls
      - *store_test_results
      - *store_test_artifacts

  build-deploy-docs:
    docker:
      - image: continuumio/miniconda3:4.7.10
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - 08:c1:46:ae:ea:06:99:b6:64:ee:3f:e0:98:ac:30:ce
      - checkout
      - *update_conda
      - *install_from_dev_requirements_py36
      - run:
          name: Install build deps
          command: |
            source activate kipoi-env
            pip install nbconvert==5.4.0 tornado==5.1.1
            pip install mkdocs git+https://github.com/kipoi/pydoc-markdown@master
      - run:
          name: Build docs
          command: |
            source activate kipoi-env
            cd docs/
            mkdir -p theme_dir/img/ipynb/
            ./render_ipynb.bash
            pydocmd build
      - run:
          name: Deploy docs
          command: .circleci/deploy_docs.bash


workflows:
  version: 2

  test:
    jobs:
      - test-py36
      - build-deploy-docs:
          requires:
            - test-py36
          filters:
            branches:
              only:
                - master
                - test_deployment_script
